### ISSUE TITLE
多说话人语音识别整体pipeline搭建的若干疑问

### ISSUE THREAD

**Issue by pyramid20002000** [alibaba-damo-academy/FunASR#603]
OS: Linux version 3.10.0-1160.el7.x86_64 Ubuntu 18.04.6 LTS [docker中]

Python/C++ Version：python gcc version 8.2.0 (GCC)

Package Version：
- pytorch ： 1.13.1
- torchaudio ：0.13.1
- modelscope ：1.6.1
- funasr version：0.5.7

Model：
- damo/speech_fsmn_vad_zh-cn-16k-common-pytorch
- damo/speech_diarization_sond-zh-cn-alimeeting-16k-n16k4-pytorch
- damo/speech_xvector_sv-zh-cn-cnceleb-16k-spk3465-pytorch
- damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch
- damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch

Command：我用的是infer.py和demo.py 里搬来的python代码 

Details：python代码

###############################################################################
# initialize the pipeline for inference
###############################################################################

# when using the raw waveform files to inference, please use the config file `sond.yaml`
# and set mode to `sond_demo`
inference_vad_pipeline = pipeline(
    task=Tasks.voice_activity_detection,
    model="damo/speech_fsmn_vad_zh-cn-16k-common-pytorch",
    model_revision=None,
    output_dir=vad_dir,
    batch_size=1,
)

# when using the raw waveform files to inference, please use the config file `sond.yaml`
# and set mode to `sond_demo`
inference_diar_pipline = pipeline(
    mode="sond_demo",
    num_workers=0,
    task=Tasks.speaker_diarization,
    diar_model_config="sond.yaml",
    model='damo/speech_diarization_sond-zh-cn-alimeeting-16k-n16k4-pytorch',
    sv_model="damo/speech_xvector_sv-zh-cn-cnceleb-16k-spk3465-pytorch",
    sv_model_revision="v1.2.2"
)

inference_vad_punc_asr_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch',
    vad_model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch',
    punc_model='damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch',
    output_dir=output_dir,
)

Error log：
目前主要有几个问题：
1： 经常报出GPU显存不足。这里有两个问题：
	1)在pipeline的interface好像没办法调batch_size
	2)我的机器上有8张GPU，其实可以并行（每个模型一个独立的gpu），但pipeline的interface好像也没有gpuid可以输入
	请问这两个参数要如何调节？
	
2：	我做的是客服电话场景，但是是单通道，也就是两个人的声音是混在一起的。
	我现在的做法是：先vad把长音频切短，然后speaker diarization把说话人分开（音频注册的片段是我自己手工截出来的），等于把短音频再切碎，最后再上asr_vad_punc进行转写
	有几个问题：
	1）egs_modelscope里好多模型名字上有online，我的场景是offline，不需要实时。我没找到带offline的，我默认没有online字样的就是offline，这样理解正确吗？
	2）在我们的单通道的音频中，有时会有多于两个人在对话，这种多人单通道的场景哪个模型比较对口？
	3）我发现，之要多于两个人，或者两个人都是女的，声音差不多的情况下，即使我手动注册了她们的声纹，speaker diarization好像也分的不是特别准。
	   ASR有错误还好办，如果谁说了啥都错了，那结果就没办法用。我分说话人的办法对吗？有准度更高的方法或者模型吗？
	4）在两个说话人声音混叠的部分，即使speaker diarization做对，好像也没做去混叠之类的操作（就是把两个人的声音各自分开）。是需要再接一个专门的模型吗？
	   我看了魔搭社区的MossFormer：https://www.modelscope.cn/models/damo/speech_mossformer_separation_temporal_8k/summary
	   这个模型是基于speaker diarization的结果做的吗？还是说又是完全独立的一套算法？
	5）另外有个多说话人语音识别模型：NPU-ASLP/speech_mfcca_asr-zh-cn-16k-alimeeting-vocab4950，这个我的理解是个ASR模型
	   它能分辨多说话人吗？我试用了一下，跑出来的结果里没有说话人信息啊？那它为啥是多说话人语音识别模型？

不好意思，新手上路，问题有点多。

**Comment by hnluo** [comment]
Q1: Currently，VAD and SOND model are not supporting batch decoding。You can refer infer.sh script for batch decoding of ASR models using multiple GPUs.

**Comment by langgz** [comment]
For the paraformer-large-long (vad+asr+punc)，the oom is due to the default value of batch_size_token. You could change it by set `batch_size_token`, like: https://github.com/alibaba-damo-academy/FunASR/pull/609/files

**Comment by pyramid20002000** [comment]
> Q1: Currently，VAD and SOND model are not supporting batch decoding。You can refer infer.sh script for batch decoding of ASR models using multiple GPUs. Q2：MFCCA model introduction can refer to the paper https://arxiv.org/abs/2210.05265

我需要的不是batch deconding，是说，比如，我把vad模型放在gpu=1，SOND模型放在gpu=2，这样两个模型可以用不同的卡，这个意思。

我在pipeline里好像没看到怎么写。
但考虑到 pytorch里都可以这样指定 os.environ['CUDA_VISIBLE_DEVICES'] = ”1“
那我在想，是否可以：
os.environ['CUDA_VISIBLE_DEVICES'] = ”1“
pipeline1 = ....
os.environ['CUDA_VISIBLE_DEVICES'] = ”2“
pipeline2 = ....
这样有用吗？能保证两个pipeline在创建和调用的时候，是在两个gpu中吗？

**Comment by liyunlongaaa** [comment]
我也对问题5好奇，多说话人的语音识别是指？真可以绕过diarizaiton出每个人的识别结果吗？

**Comment by OedoSoldier** [comment]
> 我也对问题5好奇，多说话人的语音识别是指？真可以绕过diarizaiton出每个人的识别结果吗？

识别说话人应该用这个吧：https://www.modelscope.cn/models/damo/speech_xvector_sv-zh-cn-cnceleb-16k-spk3465-pytorch/summary

**Comment by lucasjinreal** [comment]
assert all([len(example) >= 2 for example in raw_inputs]), \
AssertionError: The length of test case in raw_inputs must larger than 1 (>=2).

看不懂，我要darization 一个文件怎么弄？还必须输入两个文件？

**Comment by shixu-zz-an** [comment]
老哥搞定了吗？

**Comment by liyunlongaaa** [comment]
no，提桶跑路了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年2月28日(周五) 晚上11:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [modelscope/FunASR] 多说话人语音识别整体pipeline搭建的若干疑问 (Issue #603)


   
老哥搞定了吗？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  shixu-zz-an left a comment (modelscope/FunASR#603)
 
老哥搞定了吗？
