### ISSUE TITLE
使用官方示例代码测试文件，出现内存溢出，文件时长才4分钟

### ISSUE THREAD

**Issue by xyx361100238** [alibaba-damo-academy/FunASR#755]
OS: linux
Python/C++ Version： python 3.8.10

Package Version：pytorch、torchaudio、modelscope、funasr version（pip list）
pytorch 2.0.1+cu117
torchaudio 2.0.2+cu117
modelscope 1.7.1
funasr 0.7.0
GPU    3080 12G显存

Model：damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command： https://github.com/alibaba-damo-academy/FunASR/tree/main/egs_modelscope/asr_vad_punc   demo脚本
Details：稍微做了修改，测试rtf
Error log：torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 336.00 MiB (GPU 0; 11.77 GiB total capacity; 10.46 GiB already allocated; 168.06 MiB free; 10.53 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

测试音频：
[542962716.zip](https://github.com/alibaba-damo-academy/FunASR/files/12102557/542962716.zip)

疑问：比较好奇是不是这个音频文件有问题，我用其他比这更长的音频文件都不会出现显存溢出，这个文件就必现

**Comment by xyx361100238** [comment]
将batch_size_token改小就解决了

**Comment by langgz** [comment]
Bugfix: https://github.com/alibaba-damo-academy/FunASR/commit/3685afda47fa0d11d0edf43c6161cef690bae461
Please update funasr, and try it again.

**Comment by LauraGPT** [comment]
> 请问batch_size_token在哪里设置呢

https://alibaba-damo-academy.github.io/FunASR/en/egs_modelscope/asr/TEMPLATE/README.html#paraformer-long-model
